name: Bandit Security Scan
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  security_scan:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit Security Scan
        run: bandit -r .